### PR TITLE
Enhance artifact name #868

### LINKED ISSUE #868: Enhance the names of LTI build artifacts to make them easier to read by consumers.
Issue https://github.com/OpenLiberty/liberty-tools-intellij/issues/866 addressed a problem where the same name was used to upload artifacts for different PR builds. The names are unique but it is difficult to tell at a glance which PR build they are associated with. Here's a screenshot for one of the test builds for reference:

image

The names contain the SHA value which someone can map back to the PR if they search using the SHA to match it to the PR. Assuming that we will have builds for multiple PRs and in the near future be also building those against existing releases of LTI, the final build result from the workflow will have many artifacts with these cryptic names. It would be helpful for the consumer of these artifacts if the name included the PR number or branch (e.g. `main`) for LSP4iJ as well as the LTI branch (e.g. `main`) or tag (e.g. `24.0.12`). This would make it easier to identify what is contained in each of the artifacts.

- [x] LTI - main againts each LSP4IJ PRs
- [x] LTI - against each tag similar to LSP4IJ. (once [864](https://github.com/OpenLiberty/liberty-tools-intellij/pull/864) is merged, change the LTI-main into LTI-against each tag.)

### PR DESCRIPTION
**Pull request by anusreelakshmi934**
Fixes - Part of #868 

The Artifacts will look like:
image

### CODE REVIEW

**Comment by TrevCraw** [comment]
Hi @anusreelakshmi934 , this looks like a good start, but it only solves part of the issue described in https://github.com/OpenLiberty/liberty-tools-intellij/issues/868.

> It would be helpful for the consumer of these artifacts if the name included the PR number or branch (e.g. main) for LSP4iJ **as well as the LTI branch (e.g. main) or tag (e.g. 24.0.12).**

We should change the LTI SHA in the artifact name to a branch/tag name as well.

We may also want to consider having some sort of identifier for the project before the branch name to avoid confusion. The below may not be very clear:
- liberty-tools-intellij-main-main
- liberty-tools-intellij-main-PR-411
- liberty-tools-intellij-24.0.6-main

Maybe we should try something like:
- liberty-tools-intellij-lti:main-lsp4ij:main
- liberty-tools-intellij-lti:main-lsp4ij:PR-411
- liberty-tools-intellij-lti:24.0.6-lsp4ij:main

cc @mrglavas

**Comment by anusreelakshmi934** [comment]
> Hi @anusreelakshmi934 , this looks like a good start, but it only solves part of the issue described in #868.
> 
> > It would be helpful for the consumer of these artifacts if the name included the PR number or branch (e.g. main) for LSP4iJ **as well as the LTI branch (e.g. main) or tag (e.g. 24.0.12).**
> 
> We should change the LTI SHA in the artifact name to a branch/tag name as well.
> 
> We may also want to consider having some sort of identifier for the project before the branch name to avoid confusion. The below may not be very clear:
> 
> * liberty-tools-intellij-main-main
> * liberty-tools-intellij-main-PR-411
> * liberty-tools-intellij-24.0.6-main
> 
> Maybe we should try something like:
> 
> * liberty-tools-intellij-lti:main-lsp4ij:main
> * liberty-tools-intellij-lti:main-lsp4ij:PR-411
> * liberty-tools-intellij-lti:24.0.6-lsp4ij:main
> 
> cc @mrglavas

@TrevCraw I have modified it. Now the artifact name looks like below:
When running normal LTI build 
image

When running cron Job:
image

Now I have given `LTI-main` hardcoded. Since i do not have the changes for running LSP4iJ continuous integration builds with existing LTI releases in my branch yet. So I guess once @vaisakhkannan 's [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/864) is merged, we can specify LTI - against each tag.

**Review by aparnamichael — APPROVED** [review]
Looks good!

**Review by mrglavas — APPROVED** [review]
The artifact names look good. Thanks.

**Pull request merged**
