### PR TITLE
Handle O/S windows covering IntelliJ

### LINKED ISSUE #646: Intermittent test automation initialization failures on MacOS
The following errors have been occurring intermittently, but fairly often over the past few weeks:
```
GradleSingleModMPLSTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10M) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'sampleGradleMPLSApp')]' in 600s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getTree(ProjectFrameFixture.java:215)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.validateImportedProjectShowsInLTW(UIBotTestUtils.java:378)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.prepareEnv(SingleModMPLSTestCommon.java:319)
        at io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.setup(GradleSingleModMPLSTest.java:45)

GradleSingleModMPProjectTest STANDARD_OUT
    INFO: 2024-02-03T00:52:27.815078: prepareEnv. Entry. ProjectPath: /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle. ProjectName: singleModGradleMP

GradleSingleModMPProjectTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2M) for condition function (Failed to find 'Welcome Frame' by 'FlatWelcomeFrame type' in 120s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:34)
        at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.prepareEnv(SingleModMPProjectTestCommon.java:906)
        at io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.setup(GradleSingleModMPProjectTest.java:78)
```
Below is a list of jobs that have run into this issue:

https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7805263938/job/21289066845
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7762957374/job/21174304771
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7759122950/job/21162481094
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7758920824/job/21161788244
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7758850340/job/21161548463
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7752853985/job/21143064368
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7751536926/job/21140904867
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7472330586/job/20334283842
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7223872376/job/19683881434

### LINKED ISSUE #913: MacOS UI is obscured by O/S modal windows affecting testing
When the automated UI testing runs it starts on a fresh VM. Since it is the first boot, the O/S shows an always on top (not really modal) dialog window which says "See what's new in macOS Sonoma." Under this is another O/S dialog saying "Background items added." The second window is also always on top and it blocks visibility of the Liberty Tools button in IntelliJ. 
image

Even though IntelliJ is the selected application (has mouse focus), when the testing robot tries to click on the Liberty Tools button the click is accepted by the O/S window and the O/S settings window is opened.
image

Originally I tried to close these O/S windows using Apple Script but now I think that clicking on the same place a second time will bring IntelliJ back into focus and allow the Liberty Tools window to open in IntelliJ as expected.

### PR DESCRIPTION
**Pull request by turkeylurkey**
1. Sometimes an O/S window covers the Liberty tool window button. Need to click it and detect that it opened before continuing. If your click lands on the O/S window then the LTW will not open and an O/S window will open instead. So try clicking again to bring the IntelliJ window to the front and to open the LTW (openAndValidateLibertyToolWindow)
2. Wait for indexing right after opening the project window so it is done before other tests are run (waitForIndexing moved)
3. Added waitForIndexing to a few more tests 
4. Indexing can take up to 1 minute before it starts
5. After adding xml wait a bit before checking the file (needed to fix one failing test in SingleModLibertyLSTestCommon)
6. Add logging to two methods for future debugging
7. The Stop button in the debugger can take up to 1 minute to appear in the UI

Fixes #913
Fixes #646

### CODE REVIEW

**Review by aparnamichael — APPROVED** [review]
Looks good!!

**Comment by aparnamichael** [comment]
@turkeylurkey There is some conflicts in the build.yaml file. Pleas take a look.

**Comment by turkeylurkey** [comment]
Re: build.yaml, I'm assuming we want to remove that soon.

**Review by aparnamichael — APPROVED** [review]

**Review by TrevCraw — APPROVED** [review]

**Comment by TrevCraw** [comment]
Hi @turkeylurkey , the changes here look good, but I am wondering if you think they will still be necessary once we make the changes discussed earlier this week to enable our Liberty Tool Window to only display projects when IntelliJ has completed indexing (i.e. implement https://github.com/OpenLiberty/liberty-tools-intellij/issues/985 for the Liberty Tool Window).

**Comment by turkeylurkey** [comment]
@TrevCraw The changes may not be required anymore so they may be removed during a comprehensive review.

**Pull request merged**
