### PR TITLE
Update to support IDEA version 2023.2.*

### LINKED ISSUE #487: incompatibility with latest intellij ?
I updated Intellij this morning and now get this when trying to install the plugin:

Plugin 'Liberty Tools' (version '23.0.6') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.9559.62

### PR DESCRIPTION
**Pull request by TrevCraw**
Fixes #487 

- Update to support IDEA version 2023.2 and its subsequent fix releases
- Update development and test IDEA version to 2023.2.3
- Update `maven-test-framework` to version 232.10072.27

TODO - add note and create issue for listener leak bug
The `main-clone-oct-21` branch was created to preserve a version of `main` where the lsp4jakarta.it tests still run

### CODE REVIEW

**Review by turkeylurkey — APPROVED** [review]

**Review by mrglavas — APPROVED** [review]
Looks good. Thanks.

**Comment by mrglavas** [comment]
@TrevCraw I spoke too soon. Looks like you missed an import of the `@Ignore` annotation.

**Comment by turkeylurkey** [comment]
I was wondering why only some files had imports.

**Comment by TrevCraw** [comment]
The @Ignore annotation appears to be causing compilation issues with the GHA build. We went with another method of disabling the lsp4jakarta.it tests in this PR: https://github.com/OpenLiberty/liberty-tools-intellij/pull/542

**Pull request closed without merging**
