### PR TITLE
Refactor gradle command generator to return at the end of the method

### LINKED ISSUE #869: Refactor the code for gradle command
Make the command processing method returns at the bottom of the method. This means checking for errors first.

### PR DESCRIPTION
**Pull request by turkeylurkey**
The old code was used as inspiration for new code so this should be cleaned up to be more readable.

Fixes #869

### CODE REVIEW

**Comment by TrevCraw** [comment]
Hi @turkeylurkey, I am not clear on the motivation here. Is it just readability?

**Comment by TrevCraw** [comment]
Hi @turkeylurkey, I am not clear on the motivation here. Is it just readability?

**Comment by turkeylurkey** [comment]
It is not just readability. Someone copied the code from here to another method so I wanted to improve readability so when it is copied the new methods will be better too.

**Comment by turkeylurkey** [comment]
Also other methods in the class do return at the end and use if statements as structured in this pull request so another good reason to merge this.

**Review by TrevCraw — APPROVED** [review]

**Review by mrglavas — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
