### PR TITLE
Adding the multi-module Maven project from the Open Liberty guide for "Creating a multi-module application".

### PR DESCRIPTION
**Pull request by mrglavas**
Resolves https://github.com/OpenLiberty/liberty-tools-intellij/issues/1113

As I've stated in the `README.md`:

This application is being included in the Liberty Tools for IntelliJ repository as a reference to assist with development of features for multi-module Maven projects and is also intended for use in automated testing of those features. While support for multi-module Maven projects is still under development, Liberty Tools for IntelliJ may not behave as intended when interacting with this project.

### CODE REVIEW

**Review by dessina-devasia — COMMENTED** [review]
I've a suggestion that instead of mentioning ear, jar and war. It will be better to rename it as SampleEARModule, SampleJARModule and SampleWARModule

**Comment by mrglavas** [comment]
> I've a suggestion that instead of mentioning ear, jar and war. It will be better to rename it as SampleEARModule, SampleJARModule and SampleWARModule

@dessina-devasia This project is derived from the Open Liberty guide for creating Maven multi-module applications. I have not modified it. The names of the directories containing the modules were chosen by the guides team. I trust that they are using best practices in building these applications as we promote them as an educational resource for Liberty users. If you have suggestions for improvement to this project you should direct that to the GitHub repo for them guide. I've added a link to the repository in the README. For the purposes of our testing, we may have reasons to enhance this project beyond what is appropriate for the guide, but I'd like to keep the base of this project as close to the original as possible so that it's easy to update if/when the guide changes in the future. Also, since a Liberty user's first experience with building a Maven multi-module application may have come through their walk-through of the guide, it's in our best interest to test that this application works as expected when it's loaded into our tools.

**Comment by dessina-devasia** [comment]
@mrglavas Thanks for the clarification

**Review by dessina-devasia — APPROVED** [review]
Looks good to me

**Review by turkeylurkey — APPROVED** [review]
Now that I realize this is a guides project let's go ahead.

**Pull request merged**
