### PR TITLE
Modifications to merge IntelliJ 2024.2 and 2024.3 support changes to main

### PR DESCRIPTION
**Pull request by dessina-devasia**
Changes to merge support for IntelliJ 2024.2 and 2024.3 into the main branch.

### CODE REVIEW

**Review by anusreelakshmi934 — APPROVED** [review]
LGTM

**Review by vaisakhkannan — APPROVED** [review]
Looks good.

**Review by staicy123 — APPROVED** [review]
Looks good to me. Thanks

**Review by mrglavas — APPROVED** [review]
Looks like this contains what we expect to see in this PR. Thanks.

**Review by TrevCraw — APPROVED** [review]
Looks good!

**Pull request merged**
